const express = require('express');
const multer = require('multer');
const router = express.Router();

// Configure multer for memory storage
const upload = multer({
  storage: multer.memoryStorage(),
  limits: {
    fileSize: 5 * 1024 * 1024, // 5MB limit for images
  },
  fileFilter: (req, file, cb) => {
    // Allow only image files
    if (file.mimetype.startsWith('image/')) {
      cb(null, true);
    } else {
      cb(new Error('Only image files are allowed!'), false);
    }
  }
});

// Upload tour image to Google Drive
router.post('/tour-image', upload.single('image'), async (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).json({ 
        success: false, 
        message: 'No image uploaded' 
      });
    }

    const file = req.file;
    const fileName = `tour_${Date.now()}_${file.originalname}`;

    // Upload to Google Drive
    // XÓA: const result = await uploadImageToGoogleDrive(file, fileName);

    // XÓA: if (result.success) {
    res.json({
      success: true,
      message: 'Tour image uploaded successfully',
      data: {
        fileId: 'placeholder_file_id', // Placeholder, actual fileId will be generated by Google Drive
        fileName: fileName,
        imageUrl: 'placeholder_image_url', // Placeholder, actual download link will be generated by Google Drive
        webViewLink: 'placeholder_web_view_link', // Placeholder, actual web view link will be generated by Google Drive
        originalName: file.originalname,
        size: file.size,
        mimetype: file.mimetype
      }
    });
    // XÓA: } else {
    // XÓA:   res.status(500).json({
    // XÓA:     success: false,
    // XÓA:     message: 'Failed to upload image to Google Drive',
    // XÓA:     error: result.error
    // XÓA:   });
    // XÓA: }
  } catch (error) {
    console.error('Upload error:', error);
    res.status(500).json({
      success: false,
      message: 'Upload failed',
      error: error.message
    });
  }
});

// Upload multiple tour images
router.post('/tour-images', upload.array('images', 5), async (req, res) => {
  try {
    if (!req.files || req.files.length === 0) {
      return res.status(400).json({ 
        success: false, 
        message: 'No images uploaded' 
      });
    }

    const uploadPromises = req.files.map(async (file, index) => {
      const fileName = `tour_${Date.now()}_${index}_${file.originalname}`;
      // XÓA: return await uploadImageToGoogleDrive(file, fileName);
      return {
        success: true, // Placeholder success
        fileId: 'placeholder_file_id', // Placeholder
        fileName: fileName,
        downloadUrl: 'placeholder_download_url', // Placeholder
        webViewLink: 'placeholder_web_view_link' // Placeholder
      };
    });

    const results = await Promise.all(uploadPromises);
    const successfulUploads = results.filter(result => result.success);
    const failedUploads = results.filter(result => !result.success);

    res.json({
      success: true,
      message: `${successfulUploads.length} images uploaded successfully`,
      data: {
        successful: successfulUploads.map(result => ({
          fileId: result.fileId,
          fileName: result.fileName,
          imageUrl: result.downloadUrl,
          webViewLink: result.webViewLink
        })),
        failed: failedUploads.map(result => ({
          error: result.error
        }))
      }
    });
  } catch (error) {
    console.error('Multiple upload error:', error);
    res.status(500).json({
      success: false,
      message: 'Upload failed',
      error: error.message
    });
  }
});

// Delete tour image from Google Drive
router.delete('/tour-image/:fileId', async (req, res) => {
  try {
    const { fileId } = req.params;
    // XÓA: const result = await deleteImageFromGoogleDrive(fileId);

    // XÓA: if (result.success) {
    res.json({
      success: true,
      message: 'Tour image deleted successfully'
    });
    // XÓA: } else {
    // XÓA:   res.status(500).json({
    // XÓA:     success: false,
    // XÓA:     message: 'Failed to delete image',
    // XÓA:     error: result.error
    // XÓA:   });
    // XÓA: }
  } catch (error) {
    console.error('Delete error:', error);
    res.status(500).json({
      success: false,
      message: 'Delete failed',
      error: error.message
    });
  }
});

module.exports = router; 